<a href="https://colab.research.google.com/github/Parkseoho/DAStudy-sun2/blob/main/%EA%B3%B5%EA%B3%B5%EA%B8%B0%EA%B4%80_%EA%B8%B0%EC%83%81_seoho.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. 서울시 공공자전거 일별 대여건수 22년 1년치 데이터 불러오기

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

bike = pd.read_csv('/content/서울특별시 공공자전거 일별 대여건수_22.01-22.06.csv',encoding='cp949')

## 서울시 22년도 1년치 기상데이터 api연동 그리고 보기 편한형태로 변경

In [ ]:
import json

url = 'http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList'
params ={'serviceKey' : "key값", 'pageNo' : '1', 'numOfRows' : '365', 'dataType' : 'JSON', 'dataCd' : 'ASOS', 'dateCd' : 'DAY', 'startDt' : '20220101', 'endDt' : '20221231', 'stnIds' : '108' }

response = requests.get(url, params=params)
data = json.loads(response.text)
df = pd.json_normalize(data)
df2 = df.explode('response.body.items.item')
df2 = pd.json_normalize(df2['response.body.items.item'])

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 62 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   stnId           365 non-null    object
 1   stnNm           365 non-null    object
 2   tm              365 non-null    object
 3   avgTa           365 non-null    object
 4   minTa           365 non-null    object
 5   minTaHrmt       365 non-null    object
 6   maxTa           365 non-null    object
 7   maxTaHrmt       365 non-null    object
 8   mi10MaxRn       365 non-null    object
 9   mi10MaxRnHrmt   365 non-null    object
 10  hr1MaxRn        365 non-null    object
 11  hr1MaxRnHrmt    365 non-null    object
 12  sumRnDur        365 non-null    object
 13  sumRn           365 non-null    object
 14  maxInsWs        365 non-null    object
 15  maxInsWsWd      365 non-null    object
 16  maxInsWsHrmt    365 non-null    object
 17  maxWs           365 non-null    object
 18  maxWsWd         365 non-null    object
 19  maxWsHrmt       365 non-null    object
 20  avgWs           365 non-null    object
 21  hr24SumRws      365 non-null    object
 22  maxWd           365 non-null    object
 23  avgTd           365 non-null    object
 24  minRhm          365 non-null    object
 25  minRhmHrmt      365 non-null    object
 26  avgRhm          365 non-null    object
 27  avgPv           365 non-null    object
 28  avgPa           365 non-null    object
 29  maxPs           365 non-null    object
 30  maxPsHrmt       365 non-null    object
 31  minPs           365 non-null    object
 32  minPsHrmt       365 non-null    object
 33  avgPs           365 non-null    object
 34  ssDur           365 non-null    object
 35  sumSsHr         365 non-null    object
 36  hr1MaxIcsrHrmt  365 non-null    object
 37  hr1MaxIcsr      365 non-null    object
 38  sumGsr          365 non-null    object
 39  ddMefs          365 non-null    object
 40  ddMefsHrmt      365 non-null    object
 41  ddMes           365 non-null    object
 42  ddMesHrmt       365 non-null    object
 43  sumDpthFhsc     365 non-null    object
 44  avgTca          365 non-null    object
 45  avgLmac         365 non-null    object
 46  avgTs           365 non-null    object
 47  minTg           365 non-null    object
 48  avgCm5Te        365 non-null    object
 49  avgCm10Te       365 non-null    object
 50  avgCm20Te       365 non-null    object
 51  avgCm30Te       365 non-null    object
 52  avgM05Te        365 non-null    object
 53  avgM10Te        365 non-null    object
 54  avgM15Te        365 non-null    object
 55  avgM30Te        365 non-null    object
 56  avgM50Te        365 non-null    object
 57  sumLrgEv        365 non-null    object
 58  sumSmlEv        365 non-null    object
 59  n99Rn           365 non-null    object
 60  iscs            365 non-null    object
 61  sumFogDur       365 non-null    object
dtypes: object(62)
memory usage: 176.9+ KB

In [ ]:
df2.describe()

,stnId,stnNm,tm,avgTa,minTa,minTaHrmt,maxTa,maxTaHrmt,mi10MaxRn,mi10MaxRnHrmt,...,avgM05Te,avgM10Te,avgM15Te,avgM30Te,avgM50Te,sumLrgEv,sumSmlEv,n99Rn,iscs,sumFogDur
count,365,365,365,365,365,365,365,365,365,365,...,365,365,365,365,365,365,365,365,365,365
unique,1,1,365,223,235,222,227,200,43,61,...,186,190,188,128,59,66,90,70,209,2
top,108,서울,2022-01-01,26.8,22.0,0001,28.4,0001,,,...,1.2,26.3,23.9,10.2,19.0,1.5,1.8,,,
freq,365,365,1,6,5,8,5,21,271,304,...,26,12,10,14,32,18,16,217,155,364

In [ ]:
# 각 칼럼의 unique한 값 수치 확인 후 1인것은 상관관계 연관없으니 제거

for i in df2.columns:
  print(i, df2[i].nunique())

stnId 1
stnNm 1
tm 365
avgTa 223
minTa 235
minTaHrmt 222
maxTa 227
maxTaHrmt 200
mi10MaxRn 43
mi10MaxRnHrmt 61
hr1MaxRn 57
hr1MaxRnHrmt 61
sumRnDur 94
sumRn 73
maxInsWs 103
maxInsWsWd 15
maxInsWsHrmt 297
maxWs 56
maxWsWd 15
maxWsHrmt 293
avgWs 35
hr24SumRws 333
maxWd 13
avgTd 248
minRhm 71
minRhmHrmt 248
avgRhm 242
avgPv 201
avgPa 212
maxPs 200
maxPsHrmt 224
minPs 213
minPsHrmt 248
avgPs 220
ssDur 53
sumSsHr 116
hr1MaxIcsrHrmt 10
hr1MaxIcsr 219
sumGsr 343
ddMefs 13
ddMefsHrmt 16
ddMes 23
ddMesHrmt 17
sumDpthFhsc 13
avgTca 80
avgLmac 72
avgTs 229
minTg 238
avgCm5Te 200
avgCm10Te 200
avgCm20Te 189
avgCm30Te 177
avgM05Te 186
avgM10Te 190
avgM15Te 188
avgM30Te 128
avgM50Te 59
sumLrgEv 66
sumSmlEv 90
n99Rn 70
iscs 209
sumFogDur 2

In [ ]:
#  의미 없는 칼럼 제거
df2 = df2.drop(columns=['stnId','stnNm',"sumFogDur"])

### 자전거 대여 데이터와 기상데이터간 결합
### 그리고 간단한 상관관계 확인을 위해 데이터의 type을 float으로 바꾸고 공백인 값을 0으로 변경

In [ ]:
df_com =  df2.merge(bike,left_on='tm',right_on='대여일시')
df_com['대여건수'] = df_com['대여건수'].str.replace(',','')
df_com['대여건수'] = df_com['대여건수'].astype(int)
df_com=df_com.replace(' ',0)
df_com=df_com.replace('',0)

for i in df_com.drop(columns=['tm','iscs','대여일시','대여건수']).columns:
  df_com[i] = df_com[i].astype(float)

In [ ]:
# tm, iscs, 대여일시의 경우 숫자타입이아닌 문자타입이기때문에 제외
# 대여건수를 기준으로 각 칼럼의 상관관계 오름차순 정렬

df_com.drop(columns=['tm','iscs','대여일시']).corr()['대여건수'].sort_values(ascending=False)

대여건수              1.000000
maxTa             0.728217
avgTs             0.712753
sumLrgEv          0.681742
avgCm5Te          0.681343
sumSmlEv          0.680189
avgCm10Te         0.677810
avgTa             0.676644
avgCm20Te         0.676550
avgCm30Te         0.672461
avgM05Te          0.662671
minTa             0.634863
avgM10Te          0.627606
sumGsr            0.580140
avgTd             0.571920
avgM15Te          0.568900
hr1MaxIcsr        0.565079
minTg             0.546169
ssDur             0.524498
avgPv             0.402343
avgM30Te          0.299913
minRhmHrmt        0.281469
sumSsHr           0.280123
maxTaHrmt         0.231354
hr1MaxIcsrHrmt    0.039562
avgRhm            0.032039
maxPsHrmt         0.022895
maxWsHrmt        -0.022149
minPsHrmt        -0.047497
avgTca           -0.050530
maxInsWsHrmt     -0.053047
maxInsWsWd       -0.062612
maxWsWd          -0.073137
minRhm           -0.073348
avgM50Te         -0.074760
avgLmac          -0.120937
hr1MaxRnHrmt     -0.125595
maxWd            -0.130964
mi10MaxRnHrmt    -0.133930
mi10MaxRn        -0.148321
hr24SumRws       -0.161700
avgWs            -0.164258
hr1MaxRn         -0.172166
maxWs            -0.172623
maxInsWs         -0.209450
sumDpthFhsc      -0.228815
ddMefs           -0.229062
minTaHrmt        -0.246505
ddMefsHrmt       -0.254204
ddMesHrmt        -0.254410
n99Rn            -0.298114
sumRn            -0.303352
ddMes            -0.338038
minPs            -0.358492
avgPa            -0.372154
sumRnDur         -0.376307
avgPs            -0.392462
maxPs            -0.427605
Name: 대여건수, dtype: float64

In [ ]:
# 음의 상관관계 높은 순위
# 1. maxPs 최고 해면 기압
# 2. avgPs 평균 해면기압


# 양의 상관관계 높은 순위
# 1. maxTa : 최고 기온
# 2. avgTs : 평균 지면온도
# 3. sumLrgEv : 합계 대형증발량
# 4. avgCm5Te : 평균 5cm 지중온도
# 5. sumSmlEv : 합계 소형증발
# 6. avgCm10Te : 평균 5cm 지중온도
# 7. avgTa : 평균 기온


# - 다음주 해야할 분석
# 음의 상관관계 상위와 양의 상관관계 상위 컬럼을 기반으로 대여건수와 상관관계 분석

In [ ]:
df_com['tm'] = pd.to_datetime(df_com['tm'])
df_com['month'] = df_com['tm'].dt.month

In [ ]:
# 날씨가 추운 11월부터 점차 줄어들기 시작하며 2월까지 감소하고 3월부터 조금씩 증가세
# 월별 날씨 파악
a  = df_com.groupby('month')['대여건수'].sum().reset_index()
a

    month     대여건수
0       1  1419866
1       2  1349352
2       3  2423766
3       4  3990507
4       5  4962837
5       6  4256692
6       7  4101127
7       8  3620585
8       9  4760532
9      10  4470269
10     11  3838567
11     12  1756715

In [ ]:
b = df_com.groupby('month')['maxTa','avgTs','avgTa','maxPs','avgPs'].mean().reset_index()
b

<ipython-input-40-26d0bf24fd98>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  b = df_com.groupby('month')['maxTa','avgTs','avgTa','maxPs','avgPs'].mean().reset_index()

    month      maxTa      avgTs      avgTa        maxPs        avgPs
0       1   2.625806  -1.619355  -2.196774  1027.496774  1025.235484
1       2   3.821429   0.750000  -1.125000  1028.210714  1025.857143
2       3  12.748387   8.319355   7.654839  1020.712903  1017.316129
3       4  20.580000  18.083333  14.753333  1019.376667  1016.790000
4       5  25.022581  25.200000  19.122581  1014.316129  1011.845161
5       6  27.470000  25.833333  23.303333  1009.270000  1006.756667
6       7  31.000000  29.064516  27.329032  1007.196774  1005.167742
7       8  28.870968  26.767742  25.741935  1008.367742  1006.474194
8       9  27.243333  24.046667  22.353333  1015.273333  1012.943333
9      10  19.677419  15.696774  14.564516  1023.703226  1021.351613
10     11  15.430000   9.486667  10.030000  1023.850000  1021.153333
11     12   1.658065  -1.790323  -2.816129  1027.787097  1024.977419

In [ ]:
ab = a.merge(b,on='month')
ab.sort_values('대여건수',ascending=False)

    month     대여건수      maxTa      avgTs      avgTa        maxPs        avgPs
4       5  4962837  25.022581  25.200000  19.122581  1014.316129  1011.845161
8       9  4760532  27.243333  24.046667  22.353333  1015.273333  1012.943333
9      10  4470269  19.677419  15.696774  14.564516  1023.703226  1021.351613
5       6  4256692  27.470000  25.833333  23.303333  1009.270000  1006.756667
6       7  4101127  31.000000  29.064516  27.329032  1007.196774  1005.167742
3       4  3990507  20.580000  18.083333  14.753333  1019.376667  1016.790000
10     11  3838567  15.430000   9.486667  10.030000  1023.850000  1021.153333
7       8  3620585  28.870968  26.767742  25.741935  1008.367742  1006.474194
2       3  2423766  12.748387   8.319355   7.654839  1020.712903  1017.316129
11     12  1756715   1.658065  -1.790323  -2.816129  1027.787097  1024.977419
0       1  1419866   2.625806  -1.619355  -2.196774  1027.496774  1025.235484
1       2  1349352   3.821429   0.750000  -1.125000  1028.210714  1025.857143

In [ ]:
# 월별로 보게되면 일자별로 보게되는 것보다
# 'maxTa','avgTs','avgTa','maxPs','avgPs'의 칼럼과 더 높은 상관관계가 있음
ab.sort_values('대여건수',ascending=False).corr()['대여건수']

month    0.384347
대여건수     1.000000
maxTa    0.883929
avgTs    0.870511
avgTa    0.855076
maxPs   -0.673237
avgPs   -0.674398
Name: 대여건수, dtype: float64