<a href="https://colab.research.google.com/github/Parkseoho/DAStudy-sun2/blob/main/SEOHO/%EA%B3%B5%EA%B3%B5%EA%B8%B0%EA%B4%80_%EA%B8%B0%EC%83%81_seoho_new_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. 서울시 공공자전거 일별 대여건수 22년 1년치 데이터 불러오기

In [ ]:
import requests
import json
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np


bike = pd.read_csv('/content/자전거.csv')

In [ ]:
bike.isnull().sum()

STA_LOC        0
RENT_NM        0
STAT_DATA      0
RENT_CNT       0
RTN_CNT        0
START_INDEX    0
END_INDEX      0
dtype: int64

In [ ]:
bike.nunique()

STA_LOC          25
RENT_NM        2786
STAT_DATA       364
RENT_CNT        816
RTN_CNT         833
START_INDEX       1
END_INDEX         1
dtype: int64

In [ ]:
bike.rename(columns={
  "STA_LOC":"지역",
  "RENT_NM":"대여소명",
  "STAT_DATA":"대여일시",
  "RENT_CNT":"대여수",
  "RTN_CNT":"반납수"
},inplace=True)

In [ ]:
# nunique 값 1개인 칼럼 제거

bike = bike.iloc[:,:5]

In [ ]:
# 서울시 구별 대여소 개수
a = bike['지역'].value_counts().reset_index(name='count')
a.rename(columns={
    "index": "지역",
    "count":"대여소개수"},inplace=True)

In [ ]:
bike['대여수'] = bike['대여수'].astype(int)
bike['반납수'] = bike['반납수'].astype(int)

In [ ]:
# 대여건수 대비 반납건수
bike_group = bike.groupby('지역')['대여수','반납수'].sum()
bike_group = bike_group.reset_index()

bike_group['대여_반납_비율'] = bike_group['대여수'] / bike_group['반납수']
bike_group.sort_values('대여수',ascending=False)

<ipython-input-221-bcd10e923dee>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  bike_group = bike.groupby('지역')['대여수','반납수'].sum()

      지역      대여수      반납수  대여_반납_비율
3    강서구  5212259  5191893  1.003923
17   송파구  4055019  4041442  1.003359
19  영등포구  3695522  3638305  1.015726
8    노원구  2669572  2657136  1.004680
18   양천구  2619315  2625517  0.997638
12   마포구  2215203  2220138  0.997777
5    광진구  2172831  2138187  1.016203
1    강동구  1948972  1961871  0.993425
6    구로구  1808042  1799019  1.005016
15   성동구  1750952  1747403  1.002031
10  동대문구  1580599  1613705  0.979484
22   종로구  1545981  1471972  1.050279
0    강남구  1394618  1318609  1.057643
14   서초구  1339738  1324515  1.011493
24   중랑구  1300592  1316503  0.987914
21   은평구  1141716  1158667  0.985370
4    관악구  1124019  1105601  1.016659
16   성북구  1092003  1094666  0.997567
23    중구  1071980  1014356  1.056808
9    도봉구   949621   952300  0.997187
11   동작구   932755   936874  0.995603
20   용산구   917874   908396  1.010434
13  서대문구   896988   856941  1.046733
7    금천구   794126   787533  1.008372
2    강북구   648956   640911  1.012552

In [ ]:
a.head()

     지역  대여소개수
0   송파구  77831
1   강서구  67217
2   강남구  59481
3  영등포구  54493
4   서초구  50782

In [ ]:
bike_merge = bike_group.merge(a,on='지역')

In [ ]:
# 대여소 개수 대비 대여수 비교
#

bike_merge['대여소개수_대여수'] =  bike_merge['대여수'] / bike_merge['대여소개수']
bike_merge.sort_values('대여소개수_대여수',ascending=False)

      지역      대여수      반납수  대여_반납_비율  대여소개수  대여소개수_대여수
3    강서구  5212259  5191893  1.003923  67217  77.543761
5    광진구  2172831  2138187  1.016203  31184  69.677751
19  영등포구  3695522  3638305  1.015726  54493  67.816453
18   양천구  2619315  2625517  0.997638  39469  66.363855
8    노원구  2669572  2657136  1.004680  49151  54.313686
15   성동구  1750952  1747403  1.002031  32643  53.639433
10  동대문구  1580599  1613705  0.979484  29694  53.229575
17   송파구  4055019  4041442  1.003359  77831  52.100307
12   마포구  2215203  2220138  0.997777  43474  50.954663
1    강동구  1948972  1961871  0.993425  43052  45.270185
6    구로구  1808042  1799019  1.005016  40479  44.666173
4    관악구  1124019  1105601  1.016659  26746  42.025686
22   종로구  1545981  1471972  1.050279  37226  41.529603
24   중랑구  1300592  1316503  0.987914  33903  38.362151
16   성북구  1092003  1094666  0.997567  29493  37.025837
11   동작구   932755   936874  0.995603  25711  36.278441
9    도봉구   949621   952300  0.997187  27642  34.354280
23    중구  1071980  1014356  1.056808  31711  33.804673
21   은평구  1141716  1158667  0.985370  35211  32.424981
13  서대문구   896988   856941  1.046733  29517  30.388861
2    강북구   648956   640911  1.012552  21514  30.164358
7    금천구   794126   787533  1.008372  26891  29.531293
20   용산구   917874   908396  1.010434  32526  28.219701
14   서초구  1339738  1324515  1.011493  50782  26.382143
0    강남구  1394618  1318609  1.057643  59481  23.446445

In [ ]:
bike['대여일시_time'] = pd.to_datetime(bike['대여일시'])
bike['월'] = bike['대여일시_time'].dt.month

In [ ]:
# 혹서기나 혹한기인 날이 대여수와 반납수가 적으며 날씨가 적당한 시기에 대여수 많음

bike.groupby(['월'])['대여수','반납수'].sum().reset_index().set_index('월').sort_values('대여수',ascending=False)

<ipython-input-226-dd74c029ce24>:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  bike.groupby(['월'])['대여수','반납수'].sum().reset_index().set_index('월').sort_values('대여수',ascending=False)

        대여수      반납수
월
10  5290522  5271143
5   4950253  4928558
6   4871768  4851137
9   4546762  4525804
4   4079981  3891381
8   3933499  3918871
7   3929893  3914522
3   3883459  3864734
11  3836482  3822068
2   2230336  2221506
12  1755718  1748757
1   1570580  1563979

## 서울시 22년도 1년치 기상데이터 api연동 그리고 보기 편한형태로 변경

In [ ]:
import json

url = 'http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList'
params ={'serviceKey' : "eEvbFhr5RM6HD89cbNhhYzbPk2pTg1Ec2E2nSHN88dC8jgqzei81Fkn2xhDM4eWBPJQgSRINAuYd939p3MTsfg==", 'numOfRows' : '999', 'dataType' : 'JSON', 'dataCd' : 'ASOS', 'dateCd' : 'DAY', 'startDt' : '20221101', 'endDt' : '20231031', 'stnIds' : '108' }

response = requests.get(url, params=params)
data = json.loads(response.text)
df = pd.json_normalize(data)
df2 = df.explode('response.body.items.item')
df2 = pd.json_normalize(df2['response.body.items.item'])

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 62 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   stnId           365 non-null    object
 1   stnNm           365 non-null    object
 2   tm              365 non-null    object
 3   avgTa           365 non-null    object
 4   minTa           365 non-null    object
 5   minTaHrmt       365 non-null    object
 6   maxTa           365 non-null    object
 7   maxTaHrmt       365 non-null    object
 8   mi10MaxRn       365 non-null    object
 9   mi10MaxRnHrmt   365 non-null    object
 10  hr1MaxRn        365 non-null    object
 11  hr1MaxRnHrmt    365 non-null    object
 12  sumRnDur        365 non-null    object
 13  sumRn           365 non-null    object
 14  maxInsWs        365 non-null    object
 15  maxInsWsWd      365 non-null    object
 16  maxInsWsHrmt    365 non-null    object
 17  maxWs           365 non-null    object
 18  maxWsWd         365 non-null    object
 19  maxWsHrmt       365 non-null    object
 20  avgWs           365 non-null    object
 21  hr24SumRws      365 non-null    object
 22  maxWd           365 non-null    object
 23  avgTd           365 non-null    object
 24  minRhm          365 non-null    object
 25  minRhmHrmt      365 non-null    object
 26  avgRhm          365 non-null    object
 27  avgPv           365 non-null    object
 28  avgPa           365 non-null    object
 29  maxPs           365 non-null    object
 30  maxPsHrmt       365 non-null    object
 31  minPs           365 non-null    object
 32  minPsHrmt       365 non-null    object
 33  avgPs           365 non-null    object
 34  ssDur           365 non-null    object
 35  sumSsHr         365 non-null    object
 36  hr1MaxIcsrHrmt  365 non-null    object
 37  hr1MaxIcsr      365 non-null    object
 38  sumGsr          365 non-null    object
 39  ddMefs          365 non-null    object
 40  ddMefsHrmt      365 non-null    object
 41  ddMes           365 non-null    object
 42  ddMesHrmt       365 non-null    object
 43  sumDpthFhsc     365 non-null    object
 44  avgTca          365 non-null    object
 45  avgLmac         365 non-null    object
 46  avgTs           365 non-null    object
 47  minTg           365 non-null    object
 48  avgCm5Te        365 non-null    object
 49  avgCm10Te       365 non-null    object
 50  avgCm20Te       365 non-null    object
 51  avgCm30Te       365 non-null    object
 52  avgM05Te        365 non-null    object
 53  avgM10Te        365 non-null    object
 54  avgM15Te        365 non-null    object
 55  avgM30Te        365 non-null    object
 56  avgM50Te        365 non-null    object
 57  sumLrgEv        365 non-null    object
 58  sumSmlEv        365 non-null    object
 59  n99Rn           365 non-null    object
 60  iscs            365 non-null    object
 61  sumFogDur       365 non-null    object
dtypes: object(62)
memory usage: 176.9+ KB

In [ ]:
df2.describe()

,stnId,stnNm,tm,avgTa,minTa,minTaHrmt,maxTa,maxTaHrmt,mi10MaxRn,mi10MaxRnHrmt,...,avgM05Te,avgM10Te,avgM15Te,avgM30Te,avgM50Te,sumLrgEv,sumSmlEv,n99Rn,iscs,sumFogDur
count,365,365,365,365,365,365,365,365,365,365,...,365,365,365,365,365,365,365,365,365,365
unique,1,1,365,228,233,225,243,210,45,63,...,191,187,182,114,55,64,86,79,229,8
top,108,서울,2022-11-01,29.1,22.0,0001,28.9,0001,,,...,1.5,4.6,25.4,21.5,13.7,1.3,1.8,,,
freq,365,365,1,4,4,9,4,21,265,297,...,17,8,8,19,30,19,15,213,137,358

In [ ]:
# 각 칼럼의 unique한 값 수치 확인 후 1인것은 상관관계 연관없으니 제거

for i in df2.columns:
  print(i, df2[i].nunique())

stnId 1
stnNm 1
tm 365
avgTa 228
minTa 233
minTaHrmt 225
maxTa 243
maxTaHrmt 210
mi10MaxRn 45
mi10MaxRnHrmt 63
hr1MaxRn 58
hr1MaxRnHrmt 69
sumRnDur 98
sumRn 77
maxInsWs 99
maxInsWsWd 16
maxInsWsHrmt 296
maxWs 55
maxWsWd 16
maxWsHrmt 300
avgWs 31
hr24SumRws 329
maxWd 14
avgTd 232
minRhm 72
minRhmHrmt 251
avgRhm 244
avgPv 206
avgPa 221
maxPs 226
maxPsHrmt 207
minPs 220
minPsHrmt 248
avgPs 215
ssDur 53
sumSsHr 121
hr1MaxIcsrHrmt 10
hr1MaxIcsr 217
sumGsr 337
ddMefs 10
ddMefsHrmt 9
ddMes 19
ddMesHrmt 10
sumDpthFhsc 9
avgTca 81
avgLmac 74
avgTs 233
minTg 234
avgCm5Te 196
avgCm10Te 200
avgCm20Te 182
avgCm30Te 186
avgM05Te 191
avgM10Te 187
avgM15Te 182
avgM30Te 114
avgM50Te 55
sumLrgEv 64
sumSmlEv 86
n99Rn 79
iscs 229
sumFogDur 8

In [ ]:
#  의미 없는 칼럼 제거
df2 = df2.drop(columns=['stnId','stnNm',"sumFogDur"])

### 자전거 대여 데이터와 기상데이터간 결합
### 그리고 간단한 상관관계 확인을 위해 데이터의 type을 float으로 바꾸고 공백인 값을 0으로 변경

In [ ]:
df_com =  df2.merge(bike,left_on='tm',right_on='대여일시')

df_com=df_com.replace(' ',0)
df_com=df_com.replace('',0)

for i in df_com.drop(columns=['tm','iscs','대여일시','대여소명','대여수','지역','대여일시_time']).columns:
  df_com[i] = df_com[i].astype(float)

In [ ]:
# tm, iscs, 대여일시의 경우 숫자타입이아닌 문자타입이기때문에 제외
# 대여건수를 기준으로 각 칼럼의 상관관계 오름차순 정렬
# 일자별로 보게되면 상관관계 크게 상관이없음
df_com
df_com.drop(columns=['tm','iscs']).corr()['대여수'].sort_values(ascending=False)

<ipython-input-234-6b01297e86a5>:5: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_com.drop(columns=['tm','iscs']).corr()['대여수'].sort_values(ascending=False)

대여수               1.000000
반납수               0.978601
sumLrgEv          0.277558
sumSmlEv          0.277255
maxTa             0.266046
avgTs             0.249338
hr1MaxIcsr        0.246707
sumGsr            0.246251
avgTa             0.243135
avgCm5Te          0.231371
avgCm10Te         0.230129
avgCm20Te         0.227599
avgCm30Te         0.222966
minTa             0.217662
avgM05Te          0.215062
ssDur             0.195211
avgM10Te          0.190051
avgTd             0.189309
minTg             0.179714
avgM15Te          0.163851
avgPv             0.134997
maxTaHrmt         0.133173
sumSsHr           0.128440
minRhmHrmt        0.090571
월                 0.066245
maxWsHrmt         0.062003
avgM30Te          0.060839
maxInsWsHrmt      0.041597
maxWsWd           0.037811
maxPsHrmt         0.034359
maxInsWsWd        0.028476
maxWd             0.022529
minPsHrmt         0.010370
hr1MaxIcsrHrmt   -0.023683
avgTca           -0.045579
hr1MaxRnHrmt     -0.048024
mi10MaxRnHrmt    -0.050523
avgRhm           -0.050716
mi10MaxRn        -0.062778
minRhm           -0.069654
maxInsWs         -0.074268
ddMefs           -0.075086
sumDpthFhsc      -0.075088
maxWs            -0.078935
avgM50Te         -0.079919
ddMefsHrmt       -0.082901
ddMesHrmt        -0.083008
avgLmac          -0.083731
hr1MaxRn         -0.085338
hr24SumRws       -0.104341
avgWs            -0.104687
minTaHrmt        -0.105438
n99Rn            -0.109356
minPs            -0.116542
avgPa            -0.122902
ddMes            -0.126649
avgPs            -0.130615
sumRn            -0.140777
maxPs            -0.149906
sumRnDur         -0.181685
Name: 대여수, dtype: float64

In [ ]:
df_com['tm'] = pd.to_datetime(df_com['tm'])
df_com['month'] = df_com['tm'].dt.month

In [ ]:
a  = df_com.groupby('month')['대여수'].sum().reset_index()
a.sort_values('대여수',ascending=False)

    month      대여수
9      10  5290522
4       5  4950253
5       6  4871768
8       9  4546762
3       4  4079981
7       8  3933499
6       7  3929893
2       3  3883459
10     11  3836482
1       2  2230336
11     12  1755718
0       1  1570580

In [ ]:
# b = df_com.groupby('month').mean().reset_index() #['maxTa','avgTs','avgTa','maxPs','avgPs']
# b

In [ ]:
ab = a.merge(b,on='month')
ab.sort_values('대여수_x',ascending=False)

,month,대여수_x,avgTa,minTa,minTaHrmt,maxTa,maxTaHrmt,mi10MaxRn,mi10MaxRnHrmt,hr1MaxRn,...,avgM10Te,avgM15Te,avgM30Te,avgM50Te,sumLrgEv,sumSmlEv,n99Rn,대여수_y,반납수,월
9,10,5290522,15.795106,11.481897,1000.404365,20.995367,1443.868657,0.299644,210.034376,0.748066,...,19.871412,21.377443,21.206951,18.899811,2.597344,3.710506,1.001021,62.929963,62.699453,10.0
4,5,4950253,19.533304,14.578177,759.357423,25.093474,1361.072571,0.350029,169.991159,1.002570,...,16.281051,15.478230,12.809441,13.718800,4.390093,6.248769,4.714904,59.625798,59.364482,5.0
5,6,4871768,23.353849,19.655070,734.212724,27.866779,1460.583033,1.439976,354.563528,3.492187,...,20.642829,19.480826,14.898639,14.089287,3.930472,5.624777,6.082991,62.309979,62.046108,6.0
8,9,4546762,23.669595,20.236148,825.747605,27.626615,1355.961468,0.633494,329.471837,2.181471,...,24.960946,25.190557,21.626658,18.139524,3.050915,4.349313,4.447482,55.990469,55.732384,9.0
3,4,4079981,13.800978,8.804221,1196.859925,18.959188,1383.801964,0.350066,347.206124,0.920783,...,11.928741,11.939105,11.484098,13.889553,3.451098,4.923000,3.199823,50.454850,48.122539,4.0
7,8,3933499,27.206464,24.322646,938.444153,30.788150,1307.912127,1.710870,457.895716,3.670289,...,26.121023,25.581540,20.732697,16.898025,3.311057,4.738405,9.290304,47.084653,46.909553,8.0
6,7,3929893,26.713852,23.852152,765.820461,30.209598,1412.327149,3.304682,624.030839,6.680999,...,24.390297,23.708745,18.989786,15.507107,3.205730,4.570878,14.738153,47.066278,46.882187,7.0
2,3,3883459,9.783875,4.182932,961.083984,16.190798,1385.700623,0.000000,0.000000,0.000000,...,7.346171,8.339507,10.996748,14.699756,3.275435,4.698512,0.336940,46.460084,46.236065,3.0
10,11,3836482,10.031980,5.576012,1043.003311,15.431977,1220.141633,0.000000,0.000000,0.000000,...,15.724125,18.000706,19.587071,18.926731,1.823374,2.590015,2.803734,48.120235,47.939443,11.0
1,2,2230336,2.300453,-1.864221,1052.973804,7.290536,1441.411216,0.000000,0.000000,0.000000,...,4.003586,6.749912,12.085531,15.967704,1.750001,2.499992,0.035721,29.612257,29.495021,2.0
11,12,1755718,-2.793150,-6.550843,970.417387,1.682707,1320.709806,0.000000,0.000000,0.000000,...,9.331541,13.005242,17.399161,18.410424,1.107798,1.576213,0.440175,21.449910,21.364866,12.0
0,1,1570580,-1.506160,-5.684684,1087.386280,3.217001,1301.510472,0.000000,0.000000,0.000000,...,5.027372,8.421495,14.424847,17.349367,1.149016,1.640945,1.556886,19.113556,19.033223,1.0

In [ ]:
# 월별로 보게되면 일자별로 보게되는 것보다
# 'maxTa','avgTs','avgTa','maxPs','avgPs'의 칼럼과 더 높은 상관관계가 있음

# 음의 상관관계 높은 순위
# 1. ddMefs : 일 최심신적설
# 2. maxPs : 최고 해면 기압
# 3. minTaHrmt  : 최저 기온 시각

# 양의 상관관계 높은 순위
# 1. maxTa : 최고 기온
# 2. sumLrgEv : 합계 대형증발량
# 3. avgTa : 평균 기온


ab.sort_values('대여수_x',ascending=False).corr()['대여수_x'].sort_values(ascending=False).tail(30)

sumRn             0.321872
mi10MaxRn         0.298084
month             0.250734
월                 0.250734
avgM30Te          0.248197
minRhm            0.232641
minPsHrmt         0.203325
sumRnDur          0.112977
sumSsHr           0.041804
hr1MaxIcsrHrmt    0.011422
maxInsWs         -0.075618
maxWsWd          -0.078044
maxInsWsHrmt     -0.106730
maxWs            -0.187341
maxPsHrmt        -0.209535
maxWd            -0.244802
maxInsWsWd       -0.251855
avgM50Te         -0.254163
hr24SumRws       -0.459911
avgWs            -0.466969
minTaHrmt        -0.468766
avgPa            -0.662129
minPs            -0.666497
avgPs            -0.673904
maxPs            -0.680634
ddMes            -0.719643
ddMesHrmt        -0.748542
ddMefsHrmt       -0.748636
sumDpthFhsc      -0.772473
ddMefs           -0.772929
Name: 대여수_x, dtype: float64

In [ ]:
df_com2 = df_com[['tm','지역','대여소명','대여수','반납수','month','maxTa','sumLrgEv','avgTa','ddMefs','maxPs','minTaHrmt','sumRn']]

In [ ]:
df_com2 = df_com2.rename(columns={
    'tm':'일자',
    'month':'월',
    'maxTa':'최고기온',
    'sumLrgEv':'합계대형증발량',
    'avgTa':'평균기온',
    'ddMefs':'일최심실적설',
    'maxPs':'최고해면기압',
    'minTaHrmt':'최저기온시각',
    'sumRn' : '일강수량'
})

In [ ]:
df_com2['요일'] = df_com2['일자'].dt.day_name()
df_com2['평일주말'] = ''
df_com2.loc[df_com2['요일'].isin(['Saturday', 'Sunday']),'평일주말'] = '주말'
df_com2.loc[~df_com2['요일'].isin(['Saturday', 'Sunday']),'평일주말'] = '평일'

In [ ]:
# 전반적인 요일별 대여수를 봤을 때 대여수가 평일이 더 많음
# 이는 서울시 공공자전거는 일상적인 루틴이 많은 출퇴근, 등하교 등 많이 이용됨을 예상

df_com2.groupby('요일')['대여수'].sum().reset_index().sort_values('대여수',ascending=False)

          요일      대여수
0     Friday  6959937
1     Monday  6890244
5    Tuesday  6816434
4   Thursday  6751732
6  Wednesday  6741109
2   Saturday  5521691
3     Sunday  5198106

In [ ]:
end =df_com2[df_com2['평일주말']=='주말'].groupby(['월','평일주말'])['대여수'].sum().reset_index()
day = df_com2[df_com2['평일주말']=='평일'].groupby(['월','평일주말'])['대여수'].sum().reset_index()

In [ ]:
# 4월과 9월이 다른 월에 비해 평일 대비 주말 대여 비율이 높음

dayend = day.merge(end,on='월')
dayend['비율'] = dayend['대여수_y'] / dayend['대여수_x']
dayend.sort_values('비율',ascending=False)

     월 평일주말_x    대여수_x 평일주말_y    대여수_y        비율
3    4     평일  2800566     주말  1279415  0.456842
8    9     평일  3235634     주말  1311128  0.405215
6    7     평일  2941682     주말   988211  0.335934
9   10     평일  3975888     주말  1314634  0.330652
5    6     평일  3678343     주말  1193425  0.324446
7    8     평일  2971467     주말   962032  0.323757
1    2     평일  1722672     주말   507664  0.294696
11  12     평일  1366648     주말   389070  0.284689
2    3     평일  3037529     주말   845930  0.278493
10  11     평일  3045910     주말   790572  0.259552
0    1     평일  1271114     주말   299466  0.235593
4    5     평일  4112003     주말   838250  0.203854

In [ ]:
april = df_com2[df_com2['월']==4].groupby('일자').mean().reset_index()
april['요일'] = april['일자'].dt.day_name()
april['평일주말'] = ''
april.loc[april['요일'].isin(['Saturday', 'Sunday']),'평일주말'] = '주말'
april.loc[~april['요일'].isin(['Saturday', 'Sunday']),'평일주말'] = '평일'

<ipython-input-245-c905b1b4f978>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  april = df_com2[df_com2['월']==4].groupby('일자').mean().reset_index()

In [ ]:
april['최저기온시각'] = april['최저기온시각'].astype(int)
april['최저기온시간'] = [m / 60 % 24 for m in april['최저기온시각']]
april['대여수'] = april['대여수'].astype(int)
april['반납수'] = april['반납수'].astype(int)

In [ ]:
# 전반적으로 최저기온시각, 일강수량, 이 높을수록 대여수가 적으며 최고기온, 합계대형증발량이 높을 수록 대여수 높음

april.sort_values('대여수',ascending=False)

,일자,대여수,반납수,월,최고기온,합계대형증발량,평균기온,일최심실적설,최고해면기압,최저기온시각,일강수량,요일,평일주말,최저기온시간
2,2023-04-03,67,67,4.0,25.9,6.6,19.0,0.0,1023.4,636,0.0,Monday,평일,10.600000
18,2023-04-19,66,66,4.0,28.4,5.2,19.1,0.0,1012.6,552,0.0,Wednesday,평일,9.200000
20,2023-04-21,65,65,4.0,22.8,5.6,16.7,0.0,1015.5,621,0.0,Friday,평일,10.350000
26,2023-04-27,64,64,4.0,20.0,4.5,12.9,0.0,1021.3,610,0.0,Thursday,평일,10.166667
1,2023-04-02,64,63,4.0,25.2,6.5,18.8,0.0,1020.7,617,0.0,Sunday,주말,10.283333
0,2023-04-01,64,0,4.0,25.6,5.5,17.5,0.0,1017.4,646,0.0,Saturday,주말,10.766667
23,2023-04-24,63,62,4.0,21.3,4.1,15.8,0.0,1023.9,2349,0.0,Monday,평일,15.150000
13,2023-04-14,61,61,4.0,21.3,2.8,16.2,0.0,1016.3,30,0.0,Friday,평일,0.500000
27,2023-04-28,61,60,4.0,21.3,3.5,15.7,0.0,1019.5,613,1.9,Friday,평일,10.216667
9,2023-04-10,60,60,4.0,19.1,4.7,13.2,0.0,1018.0,526,0.0,Monday,평일,8.766667
16,2023-04-17,59,59,4.0,18.1,3.4,13.1,0.0,1016.7,541,0.0,Monday,평일,9.016667
21,2023-04-22,58,58,4.0,22.5,5.7,16.9,0.0,1021.0,559,0.0,Saturday,주말,9.316667
25,2023-04-26,56,56,4.0,13.5,2.4,10.2,0.0,1018.5,2350,0.0,Wednesday,평일,15.166667
12,2023-04-13,55,54,4.0,17.2,3.0,11.9,0.0,1019.8,611,0.0,Thursday,평일,10.183333
19,2023-04-20,55,55,4.0,18.9,1.0,15.8,0.0,1012.0,2256,0.5,Thursday,평일,13.600000
11,2023-04-12,53,52,4.0,15.3,4.9,10.1,0.0,1019.5,624,0.0,Wednesday,평일,10.400000
22,2023-04-23,52,51,4.0,22.1,5.1,16.1,0.0,1024.4,557,0.0,Sunday,주말,9.283333
6,2023-04-07,51,51,4.0,15.7,3.7,8.9,0.0,1017.9,2339,0.0,Friday,평일,14.983333
3,2023-04-04,50,50,4.0,21.7,2.8,17.6,0.0,1021.1,2352,6.9,Tuesday,평일,15.200000
7,2023-04-08,48,48,4.0,14.9,4.4,8.8,0.0,1020.5,518,0.0,Saturday,주말,8.633333
8,2023-04-09,48,48,4.0,17.8,4.3,10.8,0.0,1021.0,624,0.0,Sunday,주말,10.400000
15,2023-04-16,41,41,4.0,16.1,2.5,10.8,0.0,1010.8,529,0.0,Sunday,주말,8.816667
29,2023-04-30,41,41,4.0,17.9,3.2,12.7,0.0,1011.5,430,0.1,Sunday,주말,7.166667
17,2023-04-18,39,39,4.0,18.4,1.8,14.0,0.0,1013.7,803,1.5,Tuesday,평일,13.383333
10,2023-04-11,38,38,4.0,17.4,1.1,13.1,0.0,1015.1,2356,2.9,Tuesday,평일,15.266667
14,2023-04-15,36,35,4.0,16.6,1.5,13.5,0.0,1009.3,2359,4.6,Saturday,주말,15.316667
24,2023-04-25,32,32,4.0,13.2,1.3,10.9,0.0,1021.6,2244,0.4,Tuesday,평일,13.400000
5,2023-04-06,23,23,4.0,9.7,0.6,8.8,0.0,1012.5,2355,2.7,Thursday,평일,15.250000
28,2023-04-29,19,19,4.0,15.8,1.3,13.2,0.0,1011.7,2144,25.1,Saturday,주말,11.733333
4,2023-04-05,8,8,4.0,14.9,0.4,11.9,0.0,1014.5,2218,50.3,Wednesday,평일,12.966667

In [ ]:
# 전체 월을 비교했을 때와 특정기간에서의 상관관계는 크게 다르게 나옴
# 양의 상관관계를 보였던 부분들이 여름에는 음의상관관계

df_com2[df_com2['월'].isin([6,7,8])].groupby('월').mean().corr()

<ipython-input-280-77356c16b474>:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_com2[df_com2['월'].isin([6,7,8])].groupby('월').mean().corr()

,대여수,반납수,최고기온,합계대형증발량,평균기온,일최심실적설,최고해면기압,최저기온시각,일강수량
대여수,1.000000,1.000000,-0.982164,0.991055,-0.992952,NaN,0.417125,-0.618487,-0.808837
반납수,1.000000,1.000000,-0.982066,0.991124,-0.992891,NaN,0.416652,-0.618079,-0.809142
최고기온,-0.982164,-0.982066,1.000000,-0.948286,0.997526,NaN,-0.580572,0.755206,0.683845
합계대형증발량,0.991055,0.991124,-0.948286,1.000000,-0.968254,NaN,0.292104,-0.508087,-0.880077
평균기온,-0.992952,-0.992891,0.997526,-0.968254,1.000000,NaN,-0.521897,0.707257,0.733446
일최심실적설,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
최고해면기압,0.417125,0.416652,-0.580572,0.292104,-0.521897,NaN,1.000000,-0.972155,0.197048
최저기온시각,-0.618487,-0.618079,0.755206,-0.508087,0.707257,NaN,-0.972155,1.000000,0.038182
일강수량,-0.808837,-0.809142,0.683845,-0.880077,0.733446,NaN,0.197048,0.038182,1.000000

In [ ]:
# 여름과 겨울에서 기온의 상관관계가 정 반대로 보임


df_com2[df_com2['월'].isin([12,1,2])].groupby('월').mean().corr()

<ipython-input-281-56e30f15de6b>:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_com2[df_com2['월'].isin([12,1,2])].groupby('월').mean().corr()

,대여수,반납수,최고기온,합계대형증발량,평균기온,일최심실적설,최고해면기압,최저기온시각,일강수량
대여수,1.000000,1.000000,0.886328,0.963528,0.896516,-0.923777,0.997039,0.019761,-0.843930
반납수,1.000000,1.000000,0.886166,0.963434,0.896360,-0.923643,0.997012,0.019410,-0.844118
최고기온,0.886328,0.886166,1.000000,0.977920,0.999747,-0.996089,0.919310,0.480481,-0.499591
합계대형증발량,0.963528,0.963434,0.977920,1.000000,0.982371,-0.992560,0.981253,0.286595,-0.669592
평균기온,0.896516,0.896360,0.999747,0.982371,1.000000,-0.997824,0.927926,0.460641,-0.518942
일최심실적설,-0.923777,-0.923643,-0.996089,-0.992560,-0.997824,1.000000,-0.950487,-0.401110,0.574179
최고해면기압,0.997039,0.997012,0.919310,0.981253,0.927926,-0.950487,1.000000,0.096580,-0.800182
최저기온시각,0.019761,0.019410,0.480481,0.286595,0.460641,-0.401110,0.096580,1.000000,0.519671
일강수량,-0.843930,-0.844118,-0.499591,-0.669592,-0.518942,0.574179,-0.800182,0.519671,1.000000

In [ ]:
df_com2[df_com2['월'].isin([6,7,8])].groupby('대여소명')['대여수','반납수'].sum().sort_values('대여수',ascending=False).head(20)

<ipython-input-292-07dc96e5c78f>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df_com2[df_com2['월'].isin([6,7,8])].groupby('대여소명')['대여수','반납수'].sum().sort_values('대여수',ascending=False).head(20)

                           대여수      반납수
대여소명
2715.마곡나루역 2번 출구         53281  53468.0
4217. 한강공원 망원나들목         39603  41342.0
502. 뚝섬유원지역 1번출구 앞       36821  39544.0
1153. 발산역 1번, 9번 인근 대여소  33988  33725.0
2728.마곡나루역 3번 출구         33081  32450.0
2701. 마곡나루역 5번출구 뒤편      32300  31818.0
2102. 봉림교 교통섬            31380  32587.0
207. 여의나루역 1번출구 앞        30208  27486.0
1210. 롯데월드타워(잠실역2번출구 쪽)  29676  29649.0
1911. 구로디지털단지역 앞         28497  28538.0
230. 영등포구청역 1번출구         27008  26890.0
2177. 신대방역 2번 출구         26597  28653.0
3533. 건대입구역 사거리(롯데백화점)   23178  24471.0
1160. 양천향교역 7번출구앞        22427  22363.0
2608. 송파구청               21734  22562.0
1961. 신도림테크노근린공원         20582  20969.0
272. 당산육갑문               20440  20284.0
2622. 올림픽공원역 3번출구        20338  20283.0
247. 당산역 10번출구 앞         20282  20078.0
785.양천구청, 보건소 사잇길        20074  20420.0

In [ ]:
# 여름에는 한강공원, 여의나루, 올림픽공원 같은 곳이 높으나 겨울에는 적음

df_com2[df_com2['월'].isin([12,1,2])].groupby('대여소명')['대여수','반납수'].sum().sort_values('대여수',ascending=False).head(20)

<ipython-input-291-51bd21e6a8e3>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df_com2[df_com2['월'].isin([12,1,2])].groupby('대여소명')['대여수','반납수'].sum().sort_values('대여수',ascending=False).head(20)

                           대여수      반납수
대여소명
2715.마곡나루역 2번 출구         24947  25099.0
2701. 마곡나루역 5번출구 뒤편      18487  18574.0
1210. 롯데월드타워(잠실역2번출구 쪽)  14736  14538.0
1153. 발산역 1번, 9번 인근 대여소  14721  15292.0
2728.마곡나루역 3번 출구         14659  14445.0
230. 영등포구청역 1번출구         12892  12724.0
1911. 구로디지털단지역 앞         12221  12446.0
2102. 봉림교 교통섬            12200  12893.0
502. 뚝섬유원지역 1번출구 앞       11561  12355.0
2177. 신대방역 2번 출구         11259  11484.0
2608. 송파구청               11126  11740.0
1906. 신도림역 1번 출구 앞       10889  10879.0
1124. 발산역 6번 출구 뒤        10575  10770.0
1961. 신도림테크노근린공원         10570  11617.0
770.목동역5번출구 교통정보센터 앞     10057  10616.0
785.양천구청, 보건소 사잇길         9869  10453.0
765. 오목교역 3번출구            9857  10292.0
247. 당산역 10번출구 앞          9835  10089.0
589. 성수역3번출구              9766   9865.0
5052. 마곡역 7번출구            9623   9471.0

In [ ]:
rental = df_com2.groupby(['대여소명'])['대여수'].sum().reset_index()
retur = df_com2.groupby(['대여소명'])['반납수'].sum().reset_index()

In [ ]:
# 대여소 기준 대여보다 반납이 많은 곳을 보면 대부분 지하철역 근처
# 지하철 이용시 서울 공공자전거 많이 사용 하는것을 유추

re_merge =  rental.merge(retur,on=['대여소명'])
re_merge['반납-대여'] = re_merge['반납수'] - re_merge['대여수']
re_merge.sort_values('반납-대여',ascending=False).head(40)

                                대여소명     대여수       반납수    반납-대여
114                113. 홍대입구역 2번출구 앞   67042   82033.0  14991.0
2785              996.응암역2번출구 국민은행 앞   47887   60938.0  13051.0
2329              502. 뚝섬유원지역 1번출구 앞  135667  148302.0  12635.0
2544                  646. 장한평역 1번출구   52000   63648.0  11648.0
6              1008. 암사역 3번출구(국민은행앞)   47357   58544.0  11187.0
1225                     2719.마곡문화공원   46295   56032.0   9737.0
1871                4217. 한강공원 망원나들목  138103  147797.0   9694.0
572                  1721. 창동역 2번출구    47940   56827.0   8887.0
2716                    907. CJ 드림시티   50258   59069.0   8811.0
2354                  5082. 가양역 7번출구   55921   64329.0   8408.0
2039                      4522. 신곡시장   21438   29681.0   8243.0
1223                2717.LG유플러스 마곡사옥   55920   63523.0   7603.0
781                  2050. 노량진역 5번출구   39416   46979.0   7563.0
2484                  5858. 영등포역5번출구   59529   66966.0   7437.0
932            2262. 한신16차아파트 119동 앞   46161   53229.0   7068.0
2441                   565. 옥수역 3번출구   54920   61460.0   6540.0
711                1952. 천왕연지타운2단지 앞   17972   24469.0   6497.0
123               1141. 곰달래 문화복지센터 A   21412   27806.0   6394.0
3               1004. 삼성광나루아파트 버스정류장   21237   27608.0   6371.0
271              1308. 안암로터리 버스정류장 앞   64482   70487.0   6005.0
82                1084. 윤선생빌딩(JYP사옥)   42848   48756.0   5908.0
2735                      931. 역촌파출소   45820   51703.0   5883.0
701                  1931. 개봉역2번출구 A   21331   27094.0   5763.0
133                       1157. 강서구청   39611   45276.0   5665.0
1849                   4171. 우성아파트 앞   36380   42036.0   5656.0
2754                    956. 응암시장교차로   27102   32657.0   5555.0
1960                  4383. 푸조비즈타워 앞   24884   30423.0   5539.0
2720                      912. 응암오거리   28659   34197.0   5538.0
392                    1452. 겸재교 진입부   33458   38955.0   5497.0
1469          3533. 건대입구역 사거리(롯데백화점)   79945   85363.0   5418.0
823                      2106. 세이브마트   22178   27547.0   5369.0
2582                 712. 강월초교입구 사거리    9276   14540.0   5264.0
785                      2058. 동작경찰서   30137   35377.0   5240.0
863                 2177. 신대방역 2번 출구   90908   96059.0   5151.0
410                  147. 마포역 4번출구 뒤   37478   42599.0   5121.0
939              227. 양평2나들목 보행통로 입구   27687   32699.0   5012.0
2636                779. 신정1동 주민센터 앞   43418   48380.0   4962.0
1270                  2819.하늘숲초등학교 앞   11596   16506.0   4910.0
102   1118. 증미역 3번출구뒤(등촌두산위브센티움오피스텔)   40110   45000.0   4890.0
1738               3983. 금천구청역 1번 출구   11254   16083.0   4829.0

In [ ]:
#  대여수가 더 많은 경우는 대부분 거주지로 추정 거주지에서 대여 후 지하철역 에서 반납 예상

re_merge.sort_values('반납-대여').head(40)

                                대여소명     대여수       반납수    반납-대여
2447                   574. 아차산역4번출구   39551   22456.0 -17095.0
2581                711. 신일해피트리아파트 앞   17596    2876.0 -14720.0
797                207. 여의나루역 1번출구 앞  116361  105481.0 -10880.0
110   1126. 우장산역 1번출구옆(우장산아이파크105동앞)   27877   17086.0 -10791.0
2476                   584. 광진광장 교통섬   41393   30738.0 -10655.0
1450                3513. 상왕십리역 1번출구   29307   18942.0 -10365.0
2526               623. 서울시립대 정문 앞 B   27226   17086.0 -10140.0
552                   1692. 온곡초교 교차로   27857   18566.0  -9291.0
1219                  2712.화곡터널입구교차로   13636    4435.0  -9201.0
2096                   4591. 신길자이아파트   10875    2638.0  -8237.0
1064                 2405. 청담공원앞 교차로   12621    4413.0  -8208.0
1942               434. 신당 래미안 버스정류장    8129     509.0  -7620.0
1611                3758. 서울남부출입국관리소   28497   21166.0  -7331.0
696                  1924. 삼부르네상스파크빌   14622    7382.0  -7240.0
837                         213. KT앞   35234   28047.0  -7187.0
175                  1199. 우장산역 3번출구   24762   17680.0  -7082.0
372                       1430. 중랑구청   15343    8362.0  -6981.0
2122                   4621. 남산도서관 앞    8720    2044.0  -6676.0
369                     1428. 원묵고등학교   16350    9750.0  -6600.0
492                    162. 봉원고가차도 밑   10074    3512.0  -6562.0
2325                   497.합정동주민센터 앞   32422   25875.0  -6547.0
2591                 725. 양강중학교앞 교차로   10318    3930.0  -6388.0
1875         4221. 솔리스타오피스텔(공덕동주민센터)    8086    1873.0  -6213.0
1013            2349. 역삼빌딩 앞(하나은행 옆)    9461    3261.0  -6200.0
2587                 720. 서울강월초등학교 앞   11752    5632.0  -6120.0
1948                   436. 이대역 5번출구    9322    3409.0  -5913.0
152                1175. 대한항공 인력개발센터   20742   14833.0  -5909.0
2183          474.동대문역사문화공원역 1번출구 뒤편   29740   23861.0  -5879.0
1566               367. 독립문역 3-1번출구    19317   13470.0  -5847.0
1752                     4009. 월계프라자    9878    4035.0  -5843.0
1545              3642. LH강남힐스테이트아파트    9434    3601.0  -5833.0
664              1854. 가산아네스트 오피스텔 앞    9775    4007.0  -5768.0
799              2071. 대림아파트 후문 상가 옆    7316    1725.0  -5591.0
1080               242. 신길선원가와인아파트 앞   13885    8326.0  -5559.0
640                 1828. 한양수자인아파트 앞   11485    6030.0  -5455.0
999                2333. 양재역 3번출구 주변   14116    8682.0  -5434.0
2718               909. 백련산 힐스테이트 3차    8344    2914.0  -5430.0
83                 1085.래미안 솔베뉴(고덕로)   14546    9124.0  -5422.0
2639                     782.서남병원 후문   13419    8000.0  -5419.0
2596                733. 신정이펜하우스314동   10516    5151.0  -5365.0

In [ ]:
c = df_com2.groupby(['대여소명','평일주말'])['대여수'].sum().reset_index()
week = c[c['평일주말']=='평일'].merge(c[c['평일주말']=='주말'],on='대여소명')
week['주말_평일_대여'] = week['대여수_y'] - week['대여수_x']

In [ ]:
# 주말에 대여를 많이하는 곳은 공원과 같이 주말에 나들이 많이 하는 곳이 많음

week[week['대여수_y']>=1000].sort_values('주말_평일_대여',ascending=False).head(40)

                         대여소명 평일주말_x  대여수_x 평일주말_y  대여수_y  주말_평일_대여
670                186. 월드컵공원     평일  13409     주말  14961      1552
2780            992.북한산입구 정류장     평일   1532     주말   1334      -198
1486          3552.서울숲 공영주차장앞     평일   7116     주말   6598      -518
2138           4643. 한가람아파트 앞     평일   1881     주말   1346      -535
1872              422. 문화비축기지     평일   2216     주말   1628      -588
1123   2527.반포중학교 앞(세화여고 맞은편)     평일   2260     주말   1532      -728
2732           928. 은평역사한옥박물관     평일   2231     주말   1481      -750
1648              3804. 낙성대공원     평일   1856     주말   1062      -794
2027               451. 청와대앞길     평일   2040     주말   1096      -944
1969             440. 하늘공원 입구     평일   6119     주말   5164      -955
459          1548. 북서울 꿈의숲 서문     평일   4469     주말   3502      -967
2106  4607. 국립중앙박물관 -용산가족공원 앞     평일   2888     주말   1907      -981
2707             869.노들섬 동측 앞     평일   2851     주말   1818     -1033
2755          959. 구파발10단지 인근     평일   2186     주말   1124     -1062
1964           4389. 서울숲역3번출구     평일   2713     주말   1638     -1075
1311            299.여의도 순복음교회     평일   4388     주말   3256     -1132
2105  4605. 노들섬 다목적홀(동쪽) 숲, 앞     평일   4129     주말   2940     -1189
2133            4639. 동빙고근린공원     평일   4707     주말   3486     -1221
775            2038. 동작역 7번출구     평일   2281     주말   1044     -1237
2656         808. 서빙고동 금호맨션 앞     평일   3106     주말   1865     -1241
368           1427. 용마산역 1번출구     평일   2390     주말   1145     -1245
1804             4088. 김근태도서관     평일   2560     주말   1285     -1275
668   1858. 500번·507번 버스 종점 앞     평일   2441     주말   1110     -1331
2461               5767. 북위례2     평일   2478     주말   1055     -1423
1340          3111.무악재역 4번 출구     평일   2432     주말   1004     -1428
2443         569. 응봉현대아파트 정류소     평일   2631     주말   1186     -1445
1787     4058. 다락원체육공원 전망대 입구     평일   3799     주말   2351     -1448
355         1410. 면목 대원칸타빌아파트     평일   2622     주말   1167     -1455
2092               4585. 국회6문     평일   2477     주말   1020     -1457
2108        4609. 파크타워 104동 앞     평일   2695     주말   1237     -1458
2699            858.녹사평역3번 출구     평일   2663     주말   1195     -1468
774     2037. 동작역 5번출구 동작주차공원     평일   5134     주말   3640     -1494
850                2159. 인헌초교     평일   2720     주말   1217     -1503
1531     3624. 대모산입구역 7번 출구 앞     평일   2641     주말   1081     -1560
1489         3556.신금호파크자이APT앞     평일   2780     주말   1211     -1569
399          1459. 용마한신아파트사거리     평일   2703     주말   1126     -1577
308             1357. 북한산보국문역     평일   2737     주말   1152     -1585
2706        867.서빙고역 광장(1번출구)     평일   2856     주말   1256     -1600
1112        2516.본마을 노인복지센터 앞     평일   2848     주말   1247     -1601
341              1393.돈암육교 하단     평일   2699     주말   1053     -1646

# 총평

### 1.자전거 대여 행태
#####  └ 대부분의 대여소에서 대여수와 반납수가 비슷
#####  └ 대여가 반납보다 많은 경우는 아파트 등 주거단지 근처
#####  └ 반대로 반납이 대여보다 많은 경우는 지하철과 같은 교통 수단 근처
#####  └ 주말과 평일 비교시 평일에는 잘 보이지 않던 공원 같이 자전거 타기 좋은 곳이 높음

### 2. 자전거 대여와 날씨와의 관계
#####   └ 여름과 겨울로 비교 진행
#####   └ 여름 양의 상관관계 : 합계대형증발량, 최고해면기압
#####   └ 음의 상관관계 : 기온, 최저기온시각, 일강수량
#####   └ 겨울 양의 상관관계 : 기온, 합계대형증발량, 최고해면기압
#####   └ 겨울 음의 상관관계 : 일최심실적설, 일강수량
#####   └ 여름과 겨울 둘다 합계대형증발량, 최고해면기압 양의상관관계 가지고있으며 기온은 반대